PHONY += install
install:
	cpanm Carton
	sudo pip install mkdocs
	sudo pip install awscli
	carton install

PHONY += test
test:
	carton exec prove t/unit

PHONY += after_success
after_success:
	cd doc && mkdocs build --site-dir ../doc-site
	aws s3 sync doc-site s3://docs.moosex-dic.org/

PHONY: $(PHONY)
