PHONY += install
install:
	cpanm Carton
	sudo pip install mkdocs
	carton install

PHONY += test
test:
	carton exec prove t/unit

PHONY += after_success
after_success:
	cd doc && mkdocs build --site-dir ../doc-site

PHONY: $(PHONY)
